### ISSUE TITLE
源码org-tree.vue中关于org-tree.less文件的导入方式

### ISSUE THREAD

**Issue by wangwenyuan2006** [CrazyMrYan/vue-tree-color#2]
在源码org-tree.vue中引入org-tree.less文件是以如下方式引入的，本地开发环境运行时有时会报文件找不到的错，但将源码修改为src方式引入时，正常。
<style lang="less">
@import '../../styles/org-tree';
</style>

修改为以下正常
<style lang="less" src="../../styles/org-tree.less"></style>

**Comment by CrazyMrYan** [comment]
npm install --save-dev less less-loader
